### ISSUE TITLE
Method names on NSObject+AutoCoding should be prefixed

### ISSUE THREAD

**Issue by miklselsoe** [nicklockwood/AutoCoding#21]
All category methods (private and public) on NSObject+AutoCoding should be prefixed to avoid conflict with existing and future methods in Foundation and UIKit.

Specifically, ```- (NSDictionary*) dictionaryRepresentation``` is defined on numerous classes in Foundation and UIKit and ```- (BOOL)writeToFile:(NSString *)filePath atomically:(BOOL)useAuxiliaryFile``` conflicts with a NSArray, NSString and NSData methods with the same signature.

**Comment by nicklockwood** [comment]
It's deliberate that `writeToFile:atomically:` collides - I wanted `writeToFile:atomically:` to have the default behaviour on the classes that implement it - effectively I'm taking a standard pattern and making it work for any object, not just a few of them.

**Comment by miklselsoe** [comment]
The result of overriding methods in categories is undefined according to Apple docs and even if it works as you describe, it's not at all transparent to the user that using AutoCoding in one part of the code may affect the functionality of native calls in another part. I would classify this behavior as very risky.

From the Apple Docs:
> If the name of a method declared in a category is the same as a method in the original class, or a method in another category on the same class (or even a superclass), the behavior is undefined as to which method implementation is used at runtime. This is less likely to be an issue if you’re using categories with your own classes, but can cause problems when using categories to add methods to standard Cocoa or Cocoa Touch classes.

https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/CustomizingExistingClasses/CustomizingExistingClasses.html#//apple_ref/doc/uid/TP40011210-CH6-SW4

**Comment by nicklockwood** [comment]
I'm not overriding a method on NSObject, or one that is inherited from a superclass. I'm declaring a new method that isn't currently declared on NSObject.

NSArray, NSString and NSData, etc are then overriding *my* method, (that they inherit from NSObject), which is not undefined behaviour.

If I was declaring the AutoCoding category on NSArray, NSString or NSData, or any of their subclasses, then I'd agree with you.

**Comment by miklselsoe** [comment]
I see your point, but if Apple decides to implement ```writeToFile:atomically:``` in a category, things start going bad. Also, I still think it's problematic to use the same signature because the exact behavior is unclear.

Anyway, if you have decided that it's intended behavior, I'm not going to spend more time on it. :)
